import {
  FlankSide,
  RollEffect,
  RollResultType,
  SinglePigLanding,
} from './types.js';

export const CONFIG = Object.freeze({
  VICTORY_THRESHOLD: 100,
  SINGLE_PIG_WEIGHTS: Object.freeze([
    Object.freeze({
      landing: SinglePigLanding.FLANC,
      weight: 35,
      points: 0,
    }),
    Object.freeze({
      landing: SinglePigLanding.TROTTEUR,
      weight: 22,
      points: 5,
    }),
    Object.freeze({
      landing: SinglePigLanding.TOURNEDOS,
      weight: 22,
      points: 5,
    }),
    Object.freeze({
      landing: SinglePigLanding.GROIN_GROIN,
      weight: 13,
      points: 10,
    }),
    Object.freeze({
      landing: SinglePigLanding.BAJOUE,
      weight: 8,
      points: 15,
    }),
  ]),
  FLANK_SIDE_PROBABILITY: 0.5,
  OVERRIDE_JAMBON: 0.025,
  OVERRIDE_CHEVAL: 0.008,
  ANIMATION_DURATION_MS: 1500,
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 6,
  PLAYER_NAME_MAX_LENGTH: 30,
  HIGH_SCORE_MAX_ENTRIES: 10,
  STORAGE_KEY: 'jeu-de-cochons',
  STORAGE_SCHEMA_VERSION: 1,
  TEXTS: Object.freeze({
    appName: 'Jeu de Cochons',
    initReady: 'Jeu de Cochons prêt à être initialisé.',
    initDone: 'Jeu de Cochons initialisé.',
    missingRoot:
      'Impossible d’initialiser le jeu : l’élément racine #app est introuvable.',
    landingNames: Object.freeze({
      [SinglePigLanding.FLANC]: 'Flanc',
      [SinglePigLanding.TROTTEUR]: 'Trotteur',
      [SinglePigLanding.TOURNEDOS]: 'Tournedos',
      [SinglePigLanding.GROIN_GROIN]: 'Groin groin',
      [SinglePigLanding.BAJOUE]: 'Bajoue',
    }),
    flankSideNames: Object.freeze({
      [FlankSide.DROIT]: 'Droit',
      [FlankSide.GAUCHE]: 'Gauche',
    }),
    rollResultNames: Object.freeze({
      [RollResultType.SOMME]: 'Somme',
      [RollResultType.BON_FLANC]: 'Bon flanc',
      [RollResultType.DOUBLE_TROTTEUR]: 'Double trotteur',
      [RollResultType.DOUBLE_TOURNEDOS]: 'Double tournedos',
      [RollResultType.DOUBLE_GROIN_GROIN]: 'Double groin groin',
      [RollResultType.DOUBLE_BAJOUE]: 'Double bajoue',
      [RollResultType.COCHON_NUL]: 'Cochon nul',
      [RollResultType.BON_JAMBON]: 'Bon jambon',
      [RollResultType.COCHON_A_CHEVAL]: 'Cochon à cheval',
    }),
    rollEffectMessages: Object.freeze({
      [RollEffect.GAIN_POINTS]: 'Les points du lancé sont ajoutés au tour.',
      [RollEffect.PERTE_TOUR]: 'Les points du tour sont perdus.',
      [RollEffect.PERTE_TOTALE]: 'Le score total du joueur retombe à zéro.',
      [RollEffect.ELIMINATION]: 'Le joueur est éliminé de la partie.',
    }),
    ui: Object.freeze({
      menuTitle: 'Jeu de Cochons',
      menuIntro: 'Préparez la partie',
      playerCountLabel: 'Nombre de joueurs',
      playerNameLabel: 'Nom du joueur',
      playerNamePlaceholder: 'Joueur',
      playButton: 'Jouer',
      validationEmptyNames: 'Tous les noms doivent être renseignés.',
      validationDuplicateNames: 'Les noms des joueurs doivent être uniques.',
      gameTitle: 'Partie en cours',
      currentTurn: 'Tour en cours',
      turnScore: 'Score du tour',
      totalScore: 'Score total',
      rollButton: 'Lancer',
      rerollButton: 'Relancer',
      bankButton: 'Banker',
      skipButton: 'Passer l’animation',
      animationCanvasLabel: 'Zone d’animation du lancé',
      scoreBoardLabel: 'Scores des joueurs',
      rollHistoryTitle: 'Historique du tour',
      noRollHistory: 'Aucun lancé pour ce tour.',
      eliminated: 'Éliminé',
      activePlayer: 'Joueur actif',
      leader: 'Leader',
      pointsSuffix: 'points',
      pointSuffix: 'point',
      gainPrefix: '+',
      lossPrefix: '-',
      gameOverTitle: 'Fin de partie',
      winnerLabel: 'Gagnant',
      scoresTitle: 'Scores finaux',
      rankLabel: 'Rang',
      newGameButton: 'Nouvelle partie',
      unknownWinner: 'Aucun gagnant',
      unavailable: 'Indisponible',
      muteLabel: 'Couper le son',
      unmuteLabel: 'Rétablir le son',
      soundOnIcon: '🔊',
      soundOffIcon: '🔇',
      animationSpeedLabel: 'Vitesse d’animation',
      animationSpeedFast: 'Rapide',
      animationSpeedNormal: 'Normal',
      animationSpeedSlow: 'Lent',
    }),
  }),
});
